// Items data
export const ITEMS = [
  {
    key: 'closedDoor',
    name: 'Closed Door',
    image: 'models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.04.12_PM.png',
    model: 'models/js/closed-door28x80_baked.js',
    type: '7',
  },
  {
    key: 'openDoor',
    name: 'Open Door',
    image: 'models/thumbnails/thumbnail_Screen_Shot_2014-10-27_at_8.22.46_PM.png',
    model: 'models/js/open_door.js',
    type: '7',
  },
  {
    key: 'window',
    name: 'Window',
    image: 'models/thumbnails/thumbnail_window.png',
    model: 'models/js/whitewindow.js',
    type: '3',
  },
  {
    key: 'chair',
    name: 'Chair',
    image: 'models/thumbnails/thumbnail_Church-Chair-oak-white_1024x1024.jpg',
    model: 'models/js/gus-churchchair-whiteoak.js',
    type: '1',
  },
  {
    key: 'redChair',
    name: 'Red Chair',
    image: 'models/thumbnails/thumbnail_tn-orange.png',
    model: 'models/js/ik-ekero-orange_baked.js',
    type: '1',
  },
  {
    key: 'blueChair',
    name: 'Blue Chair',
    image: 'models/thumbnails/thumbnail_ekero-blue3.png',
    model: 'models/js/ik-ekero-blue_baked.js',
    type: '1',
  },
  {
    key: 'dresserDarkWood',
    name: 'Dresser - Dark Wood',
    image: 'models/thumbnails/thumbnail_matera_dresser_5.png',
    model: 'models/js/DWR_MATERA_DRESSER2.js',
    type: '1',
  },
  {
    key: 'dresserWhite',
    name: 'Dresser - White',
    image: 'models/thumbnails/thumbnail_img25o.jpg',
    model: 'models/js/we-narrow6white_baked.js',
    type: '1',
  },
  {
    key: 'bedsideTableShale',
    name: 'Bedside table - Shale',
    image: 'models/thumbnails/thumbnail_Blu-Dot-Shale-Bedside-Table.jpg',
    model: 'models/js/bd-shalebedside-smoke_baked.js',
    type: '1',
  },
  {
    key: 'bedsideTableWhite',
    name: 'Bedside table - White',
    image: 'models/thumbnails/thumbnail_arch-white-oval-nightstand.jpg',
    model: 'models/js/cb-archnight-white_baked.js',
    type: '1',
  },
  {
    key: 'wardrobeWhite',
    name: 'Wardrobe - White',
    image: 'models/thumbnails/thumbnail_TN-ikea-kvikine.png',
    model: 'models/js/ik-kivine_baked.js',
    type: '1',
  },
  {
    key: 'fullBed',
    name: 'Full Bed',
    image: 'models/thumbnails/thumbnail_nordli-bed-frame__0159270_PE315708_S4.JPG',
    model: 'models/js/ik_nordli_full.js',
    type: '1',
  },
  {
    key: 'bookshelf',
    name: 'Bookshelf',
    image: 'models/thumbnails/thumbnail_kendall-walnut-bookcase.jpg',
    model: 'models/js/cb-kendallbookcasewalnut_baked.js',
    type: '1',
  },
  {
    key: 'mediaConsoleWhite',
    name: 'Media Console - White',
    image: 'models/thumbnails/thumbnail_clapboard-white-60-media-console-1.jpg',
    model: 'models/js/cb-clapboard_baked.js',
    type: '1',
  },
  {
    key: 'mediaConsoleBlack',
    name: 'Media Console - Black',
    image: 'models/thumbnails/thumbnail_moore-60-media-console-1.jpg',
    model: 'models/js/cb-moore_baked.js',
    type: '1',
  },
  {
    key: 'sectionalOlive',
    name: 'Sectional - Olive',
    image: 'models/thumbnails/thumbnail_img21o.jpg',
    model: 'models/js/we-crosby2piece-greenbaked.js',
    type: '1',
  },
  {
    key: 'sofaGrey',
    name: 'Sofa - Grey',
    image: 'models/thumbnails/thumbnail_rochelle-sofa-3.jpg',
    model: 'models/js/cb-rochelle-gray_baked.js',
    type: '1',
  },
  {
    key: 'woodenTrunk',
    name: 'Wooden Trunk',
    image: 'models/thumbnails/thumbnail_teca-storage-trunk.jpg',
    model: 'models/js/cb-tecs_baked.js',
    type: '1',
  },
  {
    key: 'floorLamp',
    name: 'Floor Lamp',
    image: 'models/thumbnails/thumbnail_ore-white.png',
    model: 'models/js/ore-3legged-white_baked.js',
    type: '1',
  },
  {
    key: 'coffeeTableWood',
    name: 'Coffee Table - Wood',
    image: 'models/thumbnails/thumbnail_stockholm-coffee-table__0181245_PE332924_S4.JPG',
    model: 'models/js/ik-stockholmcoffee-brown.js',
    type: '1',
  },
  {
    key: 'sideTable',
    name: 'Side Table',
    image: 'models/thumbnails/thumbnail_Screen_Shot_2014-02-21_at_1.24.58_PM.png',
    model: 'models/js/GUSossingtonendtable.js',
    type: '1',
  },
  {
    key: 'diningTable',
    name: 'Dining Table',
    image: 'models/thumbnails/thumbnail_scholar-dining-table.jpg',
    model: 'models/js/cb-scholartable_baked.js',
    type: '1',
  },
  {
    key: 'diningTable',
    name: 'Dining table',
    image: 'models/thumbnails/thumbnail_Screen_Shot_2014-01-28_at_6.49.33_PM.png',
    model: 'models/js/BlakeAvenuejoshuatreecheftable.js',
    type: '1',
  },
  {
    key: 'blueRug',
    name: 'Blue Rug',
    image: 'models/thumbnails/thumbnail_cb-blue-block60x96.png',
    model: 'models/js/cb-blue-block-60x96.js',
    type: '8',
  },
  {
    key: 'nycPoster',
    name: 'NYC Poster',
    image: 'models/thumbnails/thumbnail_nyc2.jpg',
    model: 'models/js/nyc-poster2.js',
    type: '2',
  },
]

// Floor textures
export const FLOOR_TEXTURES = [
  {
    name: 'Light Fine Wood',
    thumbnail: 'rooms/thumbnails/thumbnail_light_fine_wood.jpg',
    url: 'rooms/textures/light_fine_wood.jpg',
    stretch: false,
    scale: 300,
  },
]

// Wall textures
export const WALL_TEXTURES = [
  {
    name: 'Marble Tiles',
    thumbnail: 'rooms/thumbnails/thumbnail_marbletiles.jpg',
    url: 'rooms/textures/marbletiles.jpg',
    stretch: false,
    scale: 300,
  },
  {
    name: 'Wallmap Yellow',
    thumbnail: 'rooms/thumbnails/thumbnail_wallmap_yellow.png',
    url: 'rooms/textures/wallmap_yellow.png',
    stretch: true,
    scale: 0,
  },
  {
    name: 'Light Brick',
    thumbnail: 'rooms/thumbnails/thumbnail_light_brick.jpg',
    url: 'rooms/textures/light_brick.jpg',
    stretch: false,
    scale: 100,
  },
]
